import type { Metadata } from "next";
import "./globals.css";
import { workSans } from "@/config/fonts";
import Providers from "@/ui/components/Providers";
import { Toaster } from "@/ui/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className} antialiased util__scroll`}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
